FROM python:3.9

WORKDIR /

COPY deploy.py deploy.py
COPY requirements.deploy.txt requirements.txt
COPY model.pkl model.pkl

RUN pip install -r requirements.txt

EXPOSE 8080

ENTRYPOINT [ "uvicorn", "deploy:server", "--host", "0.0.0.0", "--port", "8080"]